---
# DEPLOY USER
# ====================================================

- name: Add deployment user RedHat
  action: user name={{add_user}} password={{ deploy_password }}

- name: Add authorized deploy key
  authorized_key: user={{add_user}} key="{{ lookup('file', '~/.vagrant.d/insecure_public_key') }}"

- name: Remove sudo group rights
  action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add deploy user to sudoers
  action: lineinfile dest=/etc/sudoers regexp="{{add_user}} ALL" line="{{add_user}} ALL=(ALL) NOPASSWD:ALL" state=present

